### ISSUE TITLE
Ignoring and copying blade.php files

### ISSUE THREAD

**Issue by alexjacobsma** [MuriloChianfa/ioncube-encoder-action#36]
Is it possible to use this action to encode, but ignore files of a certain type in the directories specified?  Ioncube has the ability to ignore and copy.  Something like this (on windows), notice the ignore and copy params.

./ioncube_encoder82.exe --ignore '*.blade.php' --copy '*.blade.php' C:\Github\laravel_app\modules -o C:\Github\laravel_app\modules --replace-target --allow-reflection-all

Project structure I am working with-
modules
    users
        Controllers
        Models
        Views
    doors
        Controllers
        Models
        Views
ex.

What I want to do is encode all .php files in modules directory while copying blade.php files.  Is this possible using this action?  I may just be missing it.

**Comment by MuriloChianfa** [comment]
its not possible yet, but we can add this option.

**Comment by alexjacobsma** [comment]
That is great!  Please let me know if I can assist with testing.

**Comment by MuriloChianfa** [comment]
@alexjacobsma can you test the new features in the new version? v2.1.0
you can use the trial version of the ioncube to test.

MuriloChianfa/ioncube-encoder-action@v2.1.0

**Comment by alexjacobsma** [comment]
It works!  Both copy and ignore were properly passed into the command.  

Only one thing that I noticed in two places.

1. Copy and Ignore Are not recognized as valid Action Inputs.
![image](https://github.com/user-attachments/assets/128638fe-3517-4df1-97b2-75bc4be72ebb)

2. Same thing here in the warning-
![image](https://github.com/user-attachments/assets/5e66de25-54ab-4e7f-bfd0-11d2d9b81704)

But functionally, it works.  Thank you!

**Comment by MuriloChianfa** [comment]
Sorry for the inconvenient, i forgot to add the new options into the allowed inputs list.
I created a new release v2.1.1 to solve this problem.
